// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pphmrgapurhlkgjputgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwaG1yZ2FwdXJobGtnanB1dGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDYzMTQsImV4cCI6MjA2MDAyMjMxNH0.j18fewL3TVkhtC1SnVjeLCsPmuSiJxOnK7lmBO7QPos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);